$("#empezar").click(function(event){
	event.preventDefault();
	$.ajax({
		url:"../programs/juegoAjax.php",
		data:{
			materia:$("#mat-ronda").val(),
			unidades:$("#uni-ronda").val()
		},
		type:"POST",
		dataType:"text",
		success:function(data)
		{
			$("#juego").html(data);
		}
	});
});

$("#pregunta").click(function(event){
	event.preventDefault();
	$.ajax({
		url:'../programs/juegoAjax.php',
		type:"post",
		dataType:"text",
		data:{
			respAct:$("input:radio[name=opciones]:checked").val(),
			materia:$("#mat-ronda").val(),
			unidades:$("#uni-ronda").val(),
			respuesta:$("#resp-c").val(),
			
		},
		success:function(data){
			$("#juego").html(data);
		}
	});
});